param(
  [string]$HostAddress = "127.0.0.1",
  [int]$Port = 8000
)

$ErrorActionPreference = "Stop"

$projectRoot = Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")
Set-Location -LiteralPath $projectRoot

& (Join-Path $projectRoot "scripts\models\set_model_cache_env.ps1") -ProjectRoot $projectRoot | Out-Null

$env:PERSONA_RAG_MODEL_PROVIDER = "ollama"
$env:PERSONA_RAG_OLLAMA_BASE_URL = "http://127.0.0.1:11434"
$env:PERSONA_RAG_OLLAMA_MODELS_DIR = $env:OLLAMA_MODELS
$env:PERSONA_RAG_GENERATION_MODEL = "qwen3:8b"
$env:PERSONA_RAG_QUALITY_GENERATION_MODEL = "qwen3.5:9b"
$env:PERSONA_RAG_QUALITY_GENERATION_MIN_EFFORT = "high"
$env:PERSONA_RAG_QUALITY_GENERATION_THINK = "true"
$env:PERSONA_RAG_QUALITY_GENERATION_REFINE_PASSES = "0"
$env:PERSONA_RAG_LOW_GENERATION_MODEL = "qwen3.5:9b"
$env:PERSONA_RAG_MEDIUM_GENERATION_MODEL = "qwen3.5:9b"
$env:PERSONA_RAG_HIGH_GENERATION_MODEL = "qwen3.5:9b"
$env:PERSONA_RAG_LOW_GENERATION_THINK = "true"
$env:PERSONA_RAG_MEDIUM_GENERATION_THINK = "true"
$env:PERSONA_RAG_HIGH_GENERATION_THINK = "true"
$env:PERSONA_RAG_LOW_GENERATION_THINKING_BUDGET = "600"
$env:PERSONA_RAG_MEDIUM_GENERATION_THINKING_BUDGET = "2000"
$env:PERSONA_RAG_HIGH_GENERATION_THINKING_BUDGET = "4000"
$env:PERSONA_RAG_LOW_GENERATION_REFINE_PASSES = "0"
$env:PERSONA_RAG_MEDIUM_GENERATION_REFINE_PASSES = "0"
$env:PERSONA_RAG_HIGH_GENERATION_REFINE_PASSES = "0"
$env:PERSONA_RAG_MODEL_TIMEOUT_SECONDS = "480"
$env:PERSONA_RAG_MODEL_KEEP_ALIVE = "30s"
$env:PERSONA_RAG_MODEL_THINK = "true"
$env:PERSONA_RAG_MODEL_NUM_PREDICT = "1280"
$env:PERSONA_RAG_MODEL_TEMPERATURE = "0.2"
$env:PERSONA_RAG_MODEL_TOP_P = "0.9"
$env:PERSONA_RAG_BOUNDARY_FAST_PATH_ENABLED = "true"
$env:PERSONA_RAG_POST_PERSONA_ALIGNMENT_ENABLED = "true"
$env:PERSONA_RAG_FOLLOWUP_MODEL = "qwen3.5:9b"
$env:PERSONA_RAG_FOLLOWUP_THINK = "false"
$env:PERSONA_RAG_FOLLOWUP_NUM_PREDICT = "384"
$env:PERSONA_RAG_FOLLOWUP_TIMEOUT_SECONDS = "20"
$env:PERSONA_RAG_EMBEDDING_MODEL = "qwen3-embedding:0.6b"
$env:PERSONA_RAG_EMBEDDING_TIMEOUT_SECONDS = "120"
$env:PERSONA_RAG_SPARSE_RETRIEVER = "sqlite_fts5"
$env:PERSONA_RAG_RETRIEVAL_MODE = "hybrid"
$env:PERSONA_RAG_QUERY_REWRITE_ENABLED = "true"
$env:PERSONA_RAG_QUERY_REWRITE_MAX_QUERIES = "3"
$env:PERSONA_RAG_QUERY_REWRITE_DENSE = "false"
$env:PERSONA_RAG_LOCAL_RERANKER_ENABLED = "true"
$env:PERSONA_RAG_SOURCE_SELECTOR_ENABLED = "true"
$env:PERSONA_RAG_SOURCE_SELECTOR_INTENT_FILTER_ENABLED = "true"
$env:PERSONA_RAG_SOURCE_SELECTOR_TOP_K = "12"
$env:PERSONA_RAG_VECTOR_INDEX_PATH = "data/indexes/dense_qwen3_embedding_0_6b.json"
$env:PERSONA_RAG_SQLITE_PATH = "data/sqlite/persona_rag.sqlite3"
$env:PERSONA_RAG_RERANKER_BACKEND = "ollama_generate"
$env:PERSONA_RAG_RERANKER_MODEL = "dengcao/Qwen3-Reranker-0.6B:Q8_0"
$env:PERSONA_RAG_RERANKER_HF_MODEL = "Qwen/Qwen3-Reranker-0.6B"
$env:PERSONA_RAG_RERANKER_HF_CACHE_DIR = "models/huggingface"
$env:PERSONA_RAG_RERANKER_DEVICE = "auto"
$env:PERSONA_RAG_RERANKER_BATCH_SIZE = "8"
$env:PERSONA_RAG_RERANKER_ENABLED = "false"
$env:PERSONA_RAG_RERANKER_TOP_N = "12"
$env:PERSONA_RAG_RERANKER_TIMEOUT_SECONDS = "120"
$env:PERSONA_RAG_EVAL_QUESTIONS_PATH = "evals/questions/persona_benchmark_v1.json"
$env:PERSONA_RAG_AUTH_REQUIRED = "true"
$env:PERSONA_RAG_AUTH_CHALLENGE_MODE = "slider"

uv run uvicorn app.backend.main:app --host $HostAddress --port $Port
